name: Continuous Integration
on: [push]

jobs:
  build:
    name: Build and test dotnet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - run: dotnet build
      - run: dotnet test
  build-npm:
    name: Build and test npm
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./DotnetTemplate.Web
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Run npm install
        run: npm install
      - name: Run npm linter
        run: npm run lint
      - name: Run npm build
        run: npm run build
      - name: Run npm tests
        run: npm t
  build-docker-image:
    needs: [build, build-npm]
    name: Build and push docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # - name: Build image
      #   run: docker build -f Dockerfile.app -t dotnet-app .

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.app
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dotnet-app:latest

  notify-slack-succeed:
    name: Notify slack of result
    runs-on: ubuntu-latest
    needs: [build,build-npm,build-docker-image]
    steps:
      - uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: '#devops-apprenticeship'
          SLACK_USERNAME: github actions
          SLACK_COLOR: '#23b828' #green
          SLACK_TITLE: ':large_green_circle: Build succeeded for ${{ github.ref }}'
          SLACK_ICON_EMOJI: ':eyes:'
  notify-slack-failure:
    name: Notify slack of result
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    needs: [build,build-npm,build-docker-image]
    steps:
      - uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: '#devops-apprenticeship'
          SLACK_USERNAME: github actions
          SLACK_COLOR: '#d12121' #red
          SLACK_TITLE: ':red_circle: Build failed for ${{ github.ref }}'
          SLACK_ICON_EMOJI: ':eyes:'