name: Continuous Integration
on: [push]

jobs:
  build:
    name: Build and test dotnet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - run: dotnet build
      - run: dotnet test
  build-npm:
    name: Build and test npm
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./DotnetTemplate.Web
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Run npm install
        run: npm install
      - name: Run npm linter
        run: npm run lint
      - name: Run npm build
        run: npm run build
      - name: Run npm tests
        run: npm t